/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Nazlya
 */
public class EntryBlokC extends javax.swing.JFrame {

    /**
     * Creates new form EntryBlok1
     */
    public EntryBlokC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        C1MenurunRadioButton = new javax.swing.JRadioButton();
        C1TetapRadioButton = new javax.swing.JRadioButton();
        C1MeningkatRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        C220RadioButton = new javax.swing.JRadioButton();
        C240jRadioButton = new javax.swing.JRadioButton();
        C260RadioButton = new javax.swing.JRadioButton();
        C280RadioButton = new javax.swing.JRadioButton();
        C2100RadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        PenurunanLainTextField = new javax.swing.JTextField();
        C460RadioButton = new javax.swing.JRadioButton();
        C480RadioButton = new javax.swing.JRadioButton();
        C4100RadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        C420RadioButton = new javax.swing.JRadioButton();
        C440RadioButton = new javax.swing.JRadioButton();
        C4101RadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        PeningkatanLainTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        C6ModalRadioButton = new javax.swing.JRadioButton();
        C6TenagaRadioButton = new javax.swing.JRadioButton();
        C6TeknologiRadioButton = new javax.swing.JRadioButton();
        C6KapasitasRadioButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1530, 770));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(108, 145, 220));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Data Kondisi Finansial Perusahaan");

        NextButton.setBackground(new java.awt.Color(255, 102, 102));
        NextButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NextButton.setForeground(new java.awt.Color(255, 255, 255));
        NextButton.setText("Selanjutnya");
        NextButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BackButton.setBackground(new java.awt.Color(255, 102, 102));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Kembali");
        BackButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html><div style='width:200px;'>C1. Kondisi Pendapatan usaha/perusahaan saat ini dibanding sebelum Covid-19 :</div></html>");

        buttonGroup1.add(C1MenurunRadioButton);
        C1MenurunRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C1MenurunRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C1MenurunRadioButton.setText("Menurun");
        C1MenurunRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1MenurunRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(C1TetapRadioButton);
        C1TetapRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C1TetapRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C1TetapRadioButton.setText("Tetap");
        C1TetapRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1TetapRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(C1MeningkatRadioButton);
        C1MeningkatRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C1MeningkatRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C1MeningkatRadioButton.setText("Meningkat");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html><div style='width:200px;'>C2. Persen Penurunan Pendapatan Perusahaan Akibat Covid-19 :</div></html>");

        buttonGroup2.add(C220RadioButton);
        C220RadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C220RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C220RadioButton.setText("<=20%");
        C220RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C220RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(C240jRadioButton);
        C240jRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C240jRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C240jRadioButton.setText("21 - 40%");
        C240jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C240jRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(C260RadioButton);
        C260RadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C260RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C260RadioButton.setText("41 - 60%");

        buttonGroup2.add(C280RadioButton);
        C280RadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C280RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C280RadioButton.setText("61 - 80%");

        buttonGroup2.add(C2100RadioButton);
        C2100RadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C2100RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C2100RadioButton.setText("81 - 100%");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html><div style='width:220px;'>C6. Upaya Paling Utama Untuk Meningkatkan Pendapatan Perusahaan:</div></html>");

        PenurunanLainTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenurunanLainTextFieldActionPerformed(evt);
            }
        });

        buttonGroup3.add(C460RadioButton);
        C460RadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C460RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C460RadioButton.setText("41 - 60%");

        buttonGroup3.add(C480RadioButton);
        C480RadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C480RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C480RadioButton.setText("61 - 80%");

        buttonGroup3.add(C4100RadioButton);
        C4100RadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C4100RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C4100RadioButton.setText("81 - 100%");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<html><div style='width:220px;'>C4. Persen Peningkatan Pendapatan Perusahaan Akibat Covid-19 :</div></html>");

        buttonGroup3.add(C420RadioButton);
        C420RadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C420RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C420RadioButton.setText("<=20%");
        C420RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C420RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup3.add(C440RadioButton);
        C440RadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C440RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C440RadioButton.setText("21 - 40%");
        C440RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C440RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup3.add(C4101RadioButton);
        C4101RadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C4101RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C4101RadioButton.setText(">100%");
        C4101RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4101RadioButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html><div style='width:250px;'>C5. Besaran Spesifik Persen Peningkatan Pendapatan Perusahaan Akibat Covid-19 (Opsional):</div></html>");

        PeningkatanLainTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeningkatanLainTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html><div style='width:250px;'>C3. Besaran Spesifik Persen Penurunan Pendapatan Perusahaan Akibat Covid-19 (Opsional):</div></html>");

        buttonGroup4.add(C6ModalRadioButton);
        C6ModalRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C6ModalRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C6ModalRadioButton.setText("Penambahan Modal Kerja");

        buttonGroup4.add(C6TenagaRadioButton);
        C6TenagaRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C6TenagaRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C6TenagaRadioButton.setText("Penambahan Tenaga Kerja");

        buttonGroup4.add(C6TeknologiRadioButton);
        C6TeknologiRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C6TeknologiRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C6TeknologiRadioButton.setText("Peningkatan Teknologi");

        buttonGroup4.add(C6KapasitasRadioButton);
        C6KapasitasRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C6KapasitasRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        C6KapasitasRadioButton.setText("Kapasitas Produksi Meningkat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C1TetapRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C1MeningkatRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C1MenurunRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(C220RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C240jRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C260RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(C280RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C2100RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PenurunanLainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PeningkatanLainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(C420RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C440RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C460RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(C480RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C4100RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C4101RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(C6ModalRadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(C6TenagaRadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(C6TeknologiRadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(C6KapasitasRadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C420RadioButton)
                            .addComponent(C480RadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C440RadioButton)
                            .addComponent(C4100RadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C460RadioButton)
                            .addComponent(C4101RadioButton))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(C1MenurunRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C1TetapRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C1MeningkatRadioButton)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PeningkatanLainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C220RadioButton)
                            .addComponent(C280RadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C240jRadioButton)
                            .addComponent(C2100RadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C260RadioButton)))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PenurunanLainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C6ModalRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C6TenagaRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C6TeknologiRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C6KapasitasRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 830));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EntryBlokC2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 229, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 590, 830));

        setSize(new java.awt.Dimension(1429, 832));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void C1MenurunRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1MenurunRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1MenurunRadioButtonActionPerformed

    private void C220RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C220RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C220RadioButtonActionPerformed

    private void C240jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C240jRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C240jRadioButtonActionPerformed

    private void C1TetapRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1TetapRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1TetapRadioButtonActionPerformed

    private void PenurunanLainTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenurunanLainTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PenurunanLainTextFieldActionPerformed

    private void C420RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C420RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C420RadioButtonActionPerformed

    private void C440RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C440RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C440RadioButtonActionPerformed

    private void C4101RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4101RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C4101RadioButtonActionPerformed

    private void PeningkatanLainTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeningkatanLainTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PeningkatanLainTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryBlokC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryBlokC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryBlokC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryBlokC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryBlokC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton C1MeningkatRadioButton;
    private javax.swing.JRadioButton C1MenurunRadioButton;
    private javax.swing.JRadioButton C1TetapRadioButton;
    private javax.swing.JRadioButton C2100RadioButton;
    private javax.swing.JRadioButton C220RadioButton;
    private javax.swing.JRadioButton C240jRadioButton;
    private javax.swing.JRadioButton C260RadioButton;
    private javax.swing.JRadioButton C280RadioButton;
    private javax.swing.JRadioButton C4100RadioButton;
    private javax.swing.JRadioButton C4101RadioButton;
    private javax.swing.JRadioButton C420RadioButton;
    private javax.swing.JRadioButton C440RadioButton;
    private javax.swing.JRadioButton C460RadioButton;
    private javax.swing.JRadioButton C480RadioButton;
    private javax.swing.JRadioButton C6KapasitasRadioButton;
    private javax.swing.JRadioButton C6ModalRadioButton;
    private javax.swing.JRadioButton C6TeknologiRadioButton;
    private javax.swing.JRadioButton C6TenagaRadioButton;
    private javax.swing.JButton NextButton;
    private javax.swing.JTextField PeningkatanLainTextField;
    private javax.swing.JTextField PenurunanLainTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}